### ISSUE TITLE
scp_indexes resource schema docs bug - max_data_size_mb definition is incorrect

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/terraform-provider-scp#10]
Hey Team! Thanks for getting the Splunk Cloud Terraform provider off the ground!

I was going through the documentation and noticed a docs bug for the `scp_indexes` resource schema. 

The definition [HERE](https://github.com/splunk/terraform-provider-scp/blob/main/docs/resources/indexes.md#:~:text=max_data_size_mb%20(Number)%20The%20maximum%20size%20in%20MB%20for%20a%20hot%20DB%20to%20reach%20before%20a%20roll%20to%20warm%20is%20triggered.%20Defaults%20to%200%20(unlimited)) for `max_data_size_mb` is  being confused with Splunk Enterprise `indexes.conf` setting `maxDataSize` and is incorrect:

`max_data_size_mb (Number) The maximum size in MB for a hot DB to reach before a roll to warm is triggered. Defaults to 0 (unlimited)`

Splunk Cloud UI defines the intended setting as:

```
Maximum aggregated size of raw data (uncompressed) contained in index. Set this to 0 for unlimited. Max raw data size values less than 100MB, other than 0, are not allowed.
```
[ACS API docs ](https://docs.splunk.com/Documentation/SplunkCloud/9.0.2209/Config/ACSREF#Manage_indexes:~:text=index%20is%20searchable.-,maxDataSizeMB,The%20maximum%20size%20of%20the%20index%20in%20megabytes.,-splunkArchivalRetentionDays)have it listed as:

```
maxDataSizeMB | Number | The maximum size of the index in megabytes.
```

Bucket sizes are not exposed to customers and mostly not a concern for them.

Thanks!

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v1.3.9
on darwin_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- splunkcloud_indexes

`scp_indexes`

**Comment by mausam-patel** [comment]
Hi @matthewmodestino 

Thanks for reporting this! We have since updated the documentation.
