### ISSUE TITLE
Provider registry.terraform.io/splunk/scp v1.0.0 does not have a package available for your current platform, darwin_arm64

### ISSUE THREAD

**Issue by prashanthparsi** [splunk/terraform-provider-scp#15]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. 

### Terraform Version
v1.2.8

### Affected Resource(s)
Please list the resources as a list, for example:
- initialization of terraform

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```bash
terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of splunk/scp...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/splunk/scp v1.0.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different
│ platforms supported.
```
```hcl
terraform {
  required_providers {
    scp = {
      source  = "registry.terraform.io/splunk/scp"
    }
  }
}

provider "scp" {
  stack = "stack1"
  server = "https://admin.splunk.com"
}

resource "scp_indexes" "index-1" {
  name = "spk-test"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform needs to be initalized

### Actual Behavior
│ Provider registry.terraform.io/splunk/scp v1.0.0 does not have a package available for your current platform, darwin_arm64.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

Is there a provider version or packages for Apple M1 chips or OS arch type darwin/arm64

**Comment by mausam-patel** [comment]
Hi @prashanthparsi 

Interesting, I have an Apple M1 chip as well and do not encounter this error message. Have you had success with the binaries located here: https://github.com/splunk/terraform-provider-scp/releases/tag/v1.0.0?

**Comment by mausam-patel** [comment]
Closing issue after no response.
